
desezoniranje_config <- list(
  bruto_placa = list(
    category = "Bruto pla\u010da",
    base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Bruto plača/Novo",
    year_folder_pattern = "\\d{4}",
    month_folder_pattern = "\\d{2} \\d{4}",
    file_pattern = "^BP",
    table_id = "BP",
    table_name = "Bruto plače",
    expected_columns = c("Skupaj", "Zasebni sektor", "Javni sektor",
                         "Sektor država", "Javne družbe"),
    column_codes = c("period_id", "SK", "ZS", "JS", "SD", "JD"),
    description = "Bruto plače v javnem in zasebnem sektorju",
    interval = "M",
    unit = "eur"
  ),
  delovno_aktivni = list(
    category = "Trg dela",
    base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Trg dela/Delovno aktivni/Vsi",
    year_folder_pattern = "Leto \\d{4}",
    month_folder_pattern = "\\d{2} \\d{4}",
    file_pattern = "^DA",
    table_id = "DA",
    table_name = "Delovno aktivni",
    expected_columns = c("Delovno aktivni - vsi"),
    column_codes = c("period_id", "VSI"),
    description = "Delovno aktivni - vsi",
    interval = "M",
    unit = "\u0161tevilo"
  ),
  delovno_aktivni_brez_kmetov = list(
    category = "Trg dela",
    base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Trg dela/Delovno aktivni/Brez kmetov",
    year_folder_pattern = "Leto \\d{4}",
    month_folder_pattern = "\\d{2} \\d{4}",
    file_pattern = "^DA brez",
    table_id = "DA",
    table_name = "Delovno aktivni",
    expected_columns = c("DA brez kmetov"),
    column_codes = c("period_id", "BK"),
    description = "Delovno aktivni - brez kmetov",
    interval = "M",
    unit = "\u0161tevilo"
  ),
  delovno_aktivni_disagr = list(
    category = "Trg dela",
    base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Trg dela/Delovno aktivni po podpodročjih dejavnosti/Skupaj",
    year_folder_pattern = "Leto \\d{4}",
    month_folder_pattern = "\\d{2} \\d{4}",
    file_pattern = "^DA",
    table_id = "DA",
    table_name = "Delovno aktivni",
    expected_columns = c("Predelovalne", "Gradbeništvo", "Tržne storitve",
                         "Javne storitve", "Ostale storitve"),
    column_codes = c("period_id", "PR", "GR", "TS", "JS", "OS"),
    description = "Delovno aktivni po dejavnostih",
    interval = "M",
    unit = "\u0161tevilo"
  ),
  ilo_brezposelni = list(
    category = "Trg dela",
    base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Trg dela/ILO/Brezposelni",
    year_folder_pattern = "Leto \\d{4}",
    month_folder_pattern = "Q\\d \\d{4}",
    file_pattern = "^ILO",
    table_id = "ILO",
    table_name = "Brezposelnost - ILO",
    expected_columns = c("ILO brezposelni"),
    column_codes = c("period_id", "BP"),
    description = "ILO število brezposelnih",
    interval = "Q",
    unit = "\u0161tevilo"
  ),
  ilo_stopnja = list(
      category = "Trg dela",
      base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Trg dela/ILO/Stopnja brezposelnosti",
      year_folder_pattern = "Leto \\d{4}",
      month_folder_pattern = "Q\\d \\d{4}",
      file_pattern = "^Stopnja ILO",
      table_id = "ILO",
      table_name = "Brezposelnost - ILO",
      expected_columns = c("Stopnja ILO brezposelnih"),
      column_codes = c("period_id", "ST"),
      description = "ILO stopnja brezposelnih",
      interval = "Q",
      unit = "%"
    ),
  ilo_zaposleni = list(
    category = "Trg dela",
    base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Trg dela/ILO/Zaposleni",
    year_folder_pattern = "Leto \\d{4}",
    month_folder_pattern = "Q\\d \\d{4}",
    file_pattern = "^ILO Zaposleni",
    table_id = "ILO",
    table_name = "Brezposelnost - ILO",
    expected_columns = c("ILO zaposleni"),
    column_codes = c("period_id", "ZP"),
    description = "ILO število zaposlenih",
    interval = "Q",
    unit = "\u0161tevilo"
  ),
  reg_brezposelni = list(
    category = "Trg dela",
    base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Trg dela/Registrirani brezposelni/Stevilo",
    year_folder_pattern = "Leto \\d{4}",
    month_folder_pattern = "\\d{2} \\d{4}",
    file_pattern = "^Stevilo reg",
    table_id = "RB",
    table_name = "Registrirani brezposelni",
    expected_columns = c("Število reg. brezposelnih"),
    column_codes = c("period_id", "BP"),
    description = "Število registriranih brezposelnih",
    interval = "M",
    unit = "\u0161tevilo"
  ),
  reg_brezposelni_stopnja = list(
    category = "Trg dela",
    base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Trg dela/Registrirani brezposelni/Stopnje/Skupaj",
    year_folder_pattern = "Leto \\d{4}",
    month_folder_pattern = "\\d{2} \\d{4}",
    file_pattern = "^Stopnja reg",
    table_id = "RB",
    table_name = "Registrirani brezposelni",
    expected_columns = c("Stopnja brezposelnosti (v %)"),
    column_codes = c("period_id", "ST"),
    description = "Stopnja registriranih brezposelnih",
    interval = "M",
    unit = "%"
  ),
  bruto_placa_real = list(
    category = "Bruto pla\u010da",
    base_path = "\\\\192.168.38.7\\public$\\DESEZONIRANJE/Bruto plača/Novo (realne)",
    year_folder_pattern = "\\d{4}",
    month_folder_pattern = "\\d{2} \\d{4}",
    file_pattern = "^BP",
    table_id = "BPR",
    table_name = "Bruto plače realne",
    expected_columns = c("Skupaj", "Zasebni sektor", "Javni sektor",
                         "Sektor država", "Javne družbe"),
    column_codes = c("period_id", "SK", "ZS", "JS", "SD", "JD"),
    description = "Bruto plače v javnem in zasebnem sektorju - realne",
    interval = "M",
    unit = "eur"
  ),
  bruto_placa_real = list(
    category = "Realna masa neto plač",
    base_path = "\\\\192.168.38.7\\public$\\Potrošnja/realna masa neto plač",
    year_folder_pattern = "\\d{4}",
    month_folder_pattern = "\\d{2} \\d{4}",
    file_pattern = "^Realna",
    table_id = "RMNP",
    table_name = "Realna masa neto plač",
    expected_columns = c("MNP realno"),
    column_codes = c("MNPr"),
    description = "Realna masa neto plač",
    interval = "M",
    unit = "eur"
  )
)

usethis::use_data(desezoniranje_config,
                  internal = FALSE,
                  overwrite = TRUE)
